const questions = [
    "What is the capital of France?",
    "What is the capital of Germany?",
    "What's your favorite color?",
    "What's your favourite soda?",
    "How old is Elon Musk?",
    "What is the most popular programming language?",
    "What is better Javascript or Python?",
    "What is a pointer in C?",
    "What's 2+2+2+2-2*2+2+2 ?",
    "What is the most popular social media?",
    "How many continents are there?",
    "How many planets are there in our solar system?",
    "What is the biggest planet in our solar system?",
    "What is the smallest planet in our solar system?",
    "What is the most popular search engine?",
    "What is the most popular web browser?",
    "Is the Earth flat?",
    "What are the primary colors?",
    "How many continents are there on Earth?",
    "What is the capital of the United States?",
    "What is the largest planet in our solar system?",
    "How many sides does a triangle have?",
    "What is the square root of 16?",
    "Who wrote 'Romeo and Juliet'?",
    "What is the tallest mammal on Earth?",
    "What is the process called when a caterpillar turns into a butterfly?",
    "How many bones are there in the human body?",
    "Which ocean is the largest?",
    "What is the smallest prime number?",
    "What are the three states of matter?",
    "How many minutes are there in an hour?",
    "Who was the first President of the United States?",
    "What is the capital of France?",
    "How many sides does a hexagon have?",
    "What is the chemical symbol for water?",
    "What is the process called when plants make their own food?",
    "What is the main function of the heart in the human body?",
    "How many legs does a spider have?",
    "What is the opposite of 'subtract'?",
    "Who discovered America?",
    "What is the name of the biggest ocean?",
    "What is the capital of England?",
    "How many planets are there in our solar system?",
    "What is the largest organ in the human body?",
    "What is the product of 8 multiplied by 7?",
    "Who painted the Mona Lisa?",
    "How many sides does a square have?",
    "What is the chemical symbol for oxygen?",
    "What is the name of the process when water turns into vapor?",
    "What is the closest star to Earth?",
    "How many continents does the equator cross?",
    "What is the capital of China?",
    "What is the main function of the lungs in the human body?",
    "What is the name of the imaginary line that divides the Earth into the Northern and Southern Hemispheres?",
    "How many days are there in a leap year?",
    "Who wrote 'The Cat in the Hat'?",
    "What is the process called when liquid turns into a solid?",
    "What is the largest bone in the human body?",
    "What is the chemical symbol for gold?",
    "What is the highest mountain in the world?",
    "How many sides does an octagon have?",
    "What is the capital of Japan?",
    "What is the name of the largest desert in the world?",
    "How many legs does a dog have?",
    "What is the chemical symbol for carbon?",
    "What is the process called when plants take in carbon dioxide and release oxygen?",
    "What is the main function of the brain in the human body?"
]

const getRandomQuestion = () => {
    const randomIndex = Math.floor(Math.random() * questions.length);
    return questions[randomIndex];
}

module.exports = {questions, getRandomQuestion};